version: '2'
linters:
  enable:
    - errorlint
    - gocritic
    - modernize
    - paralleltest
    - thelper
    - unconvert
  settings:
    errcheck:
      check-type-assertions: true
      disable-default-exclusions: false
      verbose: true
      exclude-functions:
        - "fmt.Fprint"
        - "fmt.Fprintf"
        - "fmt.Fprintln"
        - "(*os.File).Close"
formatters:
  enable:
    - goimports
    - gofmt
  settings:
    gofmt:
      simplify: true
