// Code generated by "stringer -type OpCode"; DO NOT EDIT.

package evaluator

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpCodeNoop-0]
	_ = x[OpCodeLoadNumber-1]
	_ = x[OpCodeLoadString-2]
	_ = x[OpCodeLoadIdentifier-3]
	_ = x[OpCodeLoadGoroutineDump-4]
	_ = x[OpCodeLoadEnv-5]
	_ = x[OpCodeStoreEnv-6]
	_ = x[OpCodeLoadFieldAccessor-7]
	_ = x[OpCodeEqual-8]
	_ = x[OpCodeGreater-9]
	_ = x[OpCodeLess-10]
	_ = x[OpCodePipe-11]
	_ = x[OpCodeFunction-12]
	_ = x[OpCodeNextGoroutine-13]
	_ = x[OpCodeInitDump-14]
	_ = x[OpCodeTempDump-15]
	_ = x[OpCodePushDump-16]
	_ = x[OpCodeJumpIfTrue-17]
	_ = x[OpCodeJumpIfFalse-18]
	_ = x[OpCodeJumpTo-19]
	_ = x[OpCodeLoadAttr-20]
	_ = x[OpCodeAddGoroutine-21]
	_ = x[OpCodeRemoveGoroutine-22]
	_ = x[OpCodeStartIter-23]
	_ = x[OpCodeAssignment-24]
	_ = x[OpCodeReturn-25]
	_ = x[OpCodeContains-26]
	_ = x[OpCodePushBool-27]
	_ = x[OpCodeFuncSave-28]
	_ = x[OpCodeFuncLoad-29]
	_ = x[OpCodeFuncShowDump-30]
	_ = x[OpCodeFuncUnion-31]
	_ = x[OpCodeFuncDiff-32]
	_ = x[OpCodeFuncIntersect-33]
	_ = x[OpCodeCommandEmpty-34]
	_ = x[OpCodeCommandQuit-35]
	_ = x[OpCodeCommandHelp-36]
	_ = x[OpCodeCommandListDir-37]
	_ = x[OpCodeCommandGetWorkingDir-38]
	_ = x[OpCodeCommandVars-39]
	_ = x[OpCodeCommandChangeDir-40]
	_ = x[OpCodeCommandPragma-41]
}

const _OpCode_name = "OpCodeNoopOpCodeLoadNumberOpCodeLoadStringOpCodeLoadIdentifierOpCodeLoadGoroutineDumpOpCodeLoadEnvOpCodeStoreEnvOpCodeLoadFieldAccessorOpCodeEqualOpCodeGreaterOpCodeLessOpCodePipeOpCodeFunctionOpCodeNextGoroutineOpCodeInitDumpOpCodeTempDumpOpCodePushDumpOpCodeJumpIfTrueOpCodeJumpIfFalseOpCodeJumpToOpCodeLoadAttrOpCodeAddGoroutineOpCodeRemoveGoroutineOpCodeStartIterOpCodeAssignmentOpCodeReturnOpCodeContainsOpCodePushBoolOpCodeFuncSaveOpCodeFuncLoadOpCodeFuncShowDumpOpCodeFuncUnionOpCodeFuncDiffOpCodeFuncIntersectOpCodeCommandEmptyOpCodeCommandQuitOpCodeCommandHelpOpCodeCommandListDirOpCodeCommandGetWorkingDirOpCodeCommandVarsOpCodeCommandChangeDirOpCodeCommandPragma"

var _OpCode_index = [...]uint16{0, 10, 26, 42, 62, 85, 98, 112, 135, 146, 159, 169, 179, 193, 212, 226, 240, 254, 270, 287, 299, 313, 331, 352, 367, 383, 395, 409, 423, 437, 451, 469, 484, 498, 517, 535, 552, 569, 589, 615, 632, 654, 673}

func (i OpCode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_OpCode_index)-1 {
		return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpCode_name[_OpCode_index[idx]:_OpCode_index[idx+1]]
}
