// Code generated by "stringer -type OpCode"; DO NOT EDIT.

package evaluator

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpCodeAnd-0]
	_ = x[OpCodeOr-1]
	_ = x[OpCodeLoadNumber-2]
	_ = x[OpCodeLoadString-3]
	_ = x[OpCodeLoadIdentifier-4]
	_ = x[OpCodeLoadGoroutineDump-5]
	_ = x[OpCodeLoadEnv-6]
	_ = x[OpCodeStoreEnv-7]
	_ = x[OpCodeLoadFieldAccessor-8]
	_ = x[OpCodeEqual-9]
	_ = x[OpCodeGreater-10]
	_ = x[OpCodeLess-11]
	_ = x[OpCodePipe-12]
	_ = x[OpCodeFunction-13]
	_ = x[OpCodeNextGoroutine-14]
	_ = x[OpCodeInitDump-15]
	_ = x[OpCodeTempDump-16]
	_ = x[OpCodePushDump-17]
	_ = x[OpCodeJumpIfTrue-18]
	_ = x[OpCodeJumpIfFalse-19]
	_ = x[OpCodeJumpTo-20]
	_ = x[OpCodeLoadAttr-21]
	_ = x[OpCodeAddGoroutine-22]
	_ = x[OpCodeRemoveGoroutine-23]
	_ = x[OpCodeStartIter-24]
	_ = x[OpCodeAssignment-25]
	_ = x[OpCodeReturn-26]
	_ = x[OpCodeContains-27]
}

const _OpCode_name = "OpCodeAndOpCodeOrOpCodeLoadNumberOpCodeLoadStringOpCodeLoadIdentifierOpCodeLoadGoroutineDumpOpCodeLoadEnvOpCodeStoreEnvOpCodeLoadFieldAccessorOpCodeEqualOpCodeGreaterOpCodeLessOpCodePipeOpCodeFunctionOpCodeNextGoroutineOpCodeInitDumpOpCodeTempDumpOpCodePushDumpOpCodeJumpIfTrueOpCodeJumpIfFalseOpCodeJumpToOpCodeLoadAttrOpCodeAddGoroutineOpCodeRemoveGoroutineOpCodeStartIterOpCodeAssignmentOpCodeReturnOpCodeContains"

var _OpCode_index = [...]uint16{0, 9, 17, 33, 49, 69, 92, 105, 119, 142, 153, 166, 176, 186, 200, 219, 233, 247, 261, 277, 294, 306, 320, 338, 359, 374, 390, 402, 416}

func (i OpCode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_OpCode_index)-1 {
		return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpCode_name[_OpCode_index[idx]:_OpCode_index[idx+1]]
}
