// Code generated by "stringer -type OpCode"; DO NOT EDIT.

package evaluator

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpCodeNoop-0]
	_ = x[OpCodeLoadGoroutineDump-1]
	_ = x[OpCodeLoadFieldAccessor-2]
	_ = x[OpCodeLoadNumber-3]
	_ = x[OpCodeLoadString-4]
	_ = x[OpCodeAssignment-5]
	_ = x[OpCodePushBool-6]
	_ = x[OpCodePushDump-7]
	_ = x[OpCodeAddGoroutine-8]
	_ = x[OpCodeNextGoroutine-9]
	_ = x[OpCodeTempDump-10]
	_ = x[OpCodeContains-11]
	_ = x[OpCodeEqual-12]
	_ = x[OpCodeGreater-13]
	_ = x[OpCodeGreaterEqual-14]
	_ = x[OpCodeLess-15]
	_ = x[OpCodeLessEqual-16]
	_ = x[OpCodeNotEqual-17]
	_ = x[OpCodeJumpIfFalse-18]
	_ = x[OpCodeJumpIfTrue-19]
	_ = x[OpCodeJumpTo-20]
	_ = x[OpCodePipe-21]
	_ = x[OpCodeFuncDiff-22]
	_ = x[OpCodeFuncIntersect-23]
	_ = x[OpCodeFuncLoad-24]
	_ = x[OpCodeFuncSave-25]
	_ = x[OpCodeFuncShowDump-26]
	_ = x[OpCodeFuncUnion-27]
	_ = x[OpCodeCommandChangeDir-28]
	_ = x[OpCodeCommandEmpty-29]
	_ = x[OpCodeCommandGetWorkingDir-30]
	_ = x[OpCodeCommandHelp-31]
	_ = x[OpCodeCommandListDir-32]
	_ = x[OpCodeCommandQuit-33]
	_ = x[OpCodeCommandVars-34]
	_ = x[OpCodeCommandSetPragma-35]
	_ = x[OpCodeCommandGetPragma-36]
}

const _OpCode_name = "OpCodeNoopOpCodeLoadGoroutineDumpOpCodeLoadFieldAccessorOpCodeLoadNumberOpCodeLoadStringOpCodeAssignmentOpCodePushBoolOpCodePushDumpOpCodeAddGoroutineOpCodeNextGoroutineOpCodeTempDumpOpCodeContainsOpCodeEqualOpCodeGreaterOpCodeGreaterEqualOpCodeLessOpCodeLessEqualOpCodeNotEqualOpCodeJumpIfFalseOpCodeJumpIfTrueOpCodeJumpToOpCodePipeOpCodeFuncDiffOpCodeFuncIntersectOpCodeFuncLoadOpCodeFuncSaveOpCodeFuncShowDumpOpCodeFuncUnionOpCodeCommandChangeDirOpCodeCommandEmptyOpCodeCommandGetWorkingDirOpCodeCommandHelpOpCodeCommandListDirOpCodeCommandQuitOpCodeCommandVarsOpCodeCommandSetPragmaOpCodeCommandGetPragma"

var _OpCode_index = [...]uint16{0, 10, 33, 56, 72, 88, 104, 118, 132, 150, 169, 183, 197, 208, 221, 239, 249, 264, 278, 295, 311, 323, 333, 347, 366, 380, 394, 412, 427, 449, 467, 493, 510, 530, 547, 564, 586, 608}

func (i OpCode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_OpCode_index)-1 {
		return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpCode_name[_OpCode_index[idx]:_OpCode_index[idx+1]]
}
