package main

import (
	"flag"
	"fmt"
	"os"
	"regexp"
	"strings"
)

var re = regexp.MustCompile(`(?m)^\tOpCode([A-Za-z]+) *(// )*([A-Za-z]+)*$`)

// run with 'go generate' with the args <src> <dst>, where the source is a file
// with OpCodes and destination is the file to write a jump table to. If any
// OpCode has an inline comment, this will use that name as the name of the
// function. Otherwise the name is derived from the OpCode. For example,
// "OpCodePushBool" becomes "opPushBool".
func generate(srcPath, dstPath string) error {

	src, err := os.ReadFile(srcPath)
	if err != nil {
		return err
	}
	dst, err := os.Create(dstPath)
	if err != nil {
		return err
	}

	matches := re.FindAllStringSubmatch(string(src), -1)
	fmt.Fprintf(dst, `// Code generated by tools/jumptable; DO NOT EDIT.

package internal

// jumpTable maps OpCodes to a dispatchFn in an array so the VM's run loop can
// efficiently dispatch to handlers without a switch or hash table. Whenever
// chunk.go gets a new OpCode or the order is changed, run go generate again to
// rebuild this table.
var jumpTable = [%d]dispatchFn{
	opNoop,
`, len(matches)+1)

	for _, submatch := range matches {
		if submatch[1] == "\tOpCodePatchPlaceholder" {
			continue
		}
		if submatch[3] != "" {
			fmt.Fprintf(dst, "\t%s,\n", submatch[3])
		} else {
			suffix := strings.TrimPrefix(
				strings.TrimSpace(submatch[1]), "OpCode")
			fmt.Fprintf(dst, "\top%s,\n", suffix)
		}
	}
	fmt.Fprintln(dst, "}")
	return nil
}

func main() {
	flag.Parse()
	args := flag.Args()

	if len(args) < 2 {
		fmt.Println("expected a source and destination file")
		os.Exit(1)
	}

	err := generate(args[0], args[1])
	if err != nil {
		fmt.Println(err.Error())
		os.Exit(1)
	}
}
