// Code generated by tools/jumptable; DO NOT EDIT.

package internal

// jumpTable maps OpCodes to a dispatchFn in an array so the VM's run loop can
// efficiently dispatch to handlers without a switch or hash table. Whenever
// chunk.go gets a new OpCode or the order is changed, run go generate again to
// rebuild this table.
var jumpTable = [40]dispatchFn{
	opNoop,
	opLoadGoroutineDump,
	opLoadFieldAccessor,
	opLoadNumber,
	opLoadString,
	opAssignment,
	opPushBool,
	opPushDump,
	opAddGoroutine,
	opNextGoroutine,
	opTempDump,
	opContains,
	opContains,
	opRegexMatches,
	opRegexMatches,
	opComparison,
	opComparison,
	opComparison,
	opComparison,
	opComparison,
	opComparison,
	opConditionalJump,
	opConditionalJump,
	opJumpTo,
	opFuncDiff,
	opFuncIntersect,
	opFuncLoad,
	opFuncSave,
	opFuncShowDump,
	opFuncJSON,
	opFuncUnion,
	opCommandChangeDir,
	opCommandEmpty,
	opCommandGetWorkingDir,
	opCommandHelp,
	opCommandListDir,
	opCommandQuit,
	opCommandVars,
	opCommandSetPragma,
	opCommandGetPragma,
}
