// Code generated by "stringer -type OpCode"; DO NOT EDIT.

package internal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpCodeNoop-0]
	_ = x[OpCodeLoadGoroutineDump-1]
	_ = x[OpCodeLoadFieldAccessor-2]
	_ = x[OpCodeLoadNumber-3]
	_ = x[OpCodeLoadString-4]
	_ = x[OpCodeAssignment-5]
	_ = x[OpCodePushBool-6]
	_ = x[OpCodePushDump-7]
	_ = x[OpCodeAddGoroutine-8]
	_ = x[OpCodeNextGoroutine-9]
	_ = x[OpCodeTempDump-10]
	_ = x[OpCodeContains-11]
	_ = x[OpCodeIn-12]
	_ = x[OpCodeRegexMatches-13]
	_ = x[OpCodeRegexNotMatches-14]
	_ = x[OpCodeEqual-15]
	_ = x[OpCodeGreater-16]
	_ = x[OpCodeGreaterEqual-17]
	_ = x[OpCodeLess-18]
	_ = x[OpCodeLessEqual-19]
	_ = x[OpCodeNotEqual-20]
	_ = x[OpCodeJumpIfFalse-21]
	_ = x[OpCodeJumpIfTrue-22]
	_ = x[OpCodeJumpTo-23]
	_ = x[OpCodeFuncDiff-24]
	_ = x[OpCodeFuncIntersect-25]
	_ = x[OpCodeFuncLoad-26]
	_ = x[OpCodeFuncSave-27]
	_ = x[OpCodeFuncShowDump-28]
	_ = x[OpCodeFuncUnion-29]
	_ = x[OpCodeCommandChangeDir-30]
	_ = x[OpCodeCommandEmpty-31]
	_ = x[OpCodeCommandGetWorkingDir-32]
	_ = x[OpCodeCommandHelp-33]
	_ = x[OpCodeCommandListDir-34]
	_ = x[OpCodeCommandQuit-35]
	_ = x[OpCodeCommandVars-36]
	_ = x[OpCodeCommandSetPragma-37]
	_ = x[OpCodeCommandGetPragma-38]
}

const _OpCode_name = "OpCodeNoopOpCodeLoadGoroutineDumpOpCodeLoadFieldAccessorOpCodeLoadNumberOpCodeLoadStringOpCodeAssignmentOpCodePushBoolOpCodePushDumpOpCodeAddGoroutineOpCodeNextGoroutineOpCodeTempDumpOpCodeContainsOpCodeInOpCodeRegexMatchesOpCodeRegexNotMatchesOpCodeEqualOpCodeGreaterOpCodeGreaterEqualOpCodeLessOpCodeLessEqualOpCodeNotEqualOpCodeJumpIfFalseOpCodeJumpIfTrueOpCodeJumpToOpCodeFuncDiffOpCodeFuncIntersectOpCodeFuncLoadOpCodeFuncSaveOpCodeFuncShowDumpOpCodeFuncUnionOpCodeCommandChangeDirOpCodeCommandEmptyOpCodeCommandGetWorkingDirOpCodeCommandHelpOpCodeCommandListDirOpCodeCommandQuitOpCodeCommandVarsOpCodeCommandSetPragmaOpCodeCommandGetPragma"

var _OpCode_index = [...]uint16{0, 10, 33, 56, 72, 88, 104, 118, 132, 150, 169, 183, 197, 205, 223, 244, 255, 268, 286, 296, 311, 325, 342, 358, 370, 384, 403, 417, 431, 449, 464, 486, 504, 530, 547, 567, 584, 601, 623, 645}

func (i OpCode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_OpCode_index)-1 {
		return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpCode_name[_OpCode_index[idx]:_OpCode_index[idx+1]]
}
