// Code generated by "stringer -type OpCode"; DO NOT EDIT.

package internal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpCodeNoop-0]
	_ = x[OpCodeLoadGoroutineDump-1]
	_ = x[OpCodeLoadFieldAccessor-2]
	_ = x[OpCodeLoadNumber-3]
	_ = x[OpCodeLoadString-4]
	_ = x[OpCodeAssignment-5]
	_ = x[OpCodePushBool-6]
	_ = x[OpCodePushDump-7]
	_ = x[OpCodeAddGoroutine-8]
	_ = x[OpCodeNextGoroutine-9]
	_ = x[OpCodeTempDump-10]
	_ = x[OpCodeContains-11]
	_ = x[OpCodeRegexMatches-12]
	_ = x[OpCodeRegexNotMatches-13]
	_ = x[OpCodeEqual-14]
	_ = x[OpCodeGreater-15]
	_ = x[OpCodeGreaterEqual-16]
	_ = x[OpCodeLess-17]
	_ = x[OpCodeLessEqual-18]
	_ = x[OpCodeNotEqual-19]
	_ = x[OpCodeJumpIfFalse-20]
	_ = x[OpCodeJumpIfTrue-21]
	_ = x[OpCodeJumpTo-22]
	_ = x[OpCodeFuncDiff-23]
	_ = x[OpCodeFuncIntersect-24]
	_ = x[OpCodeFuncLoad-25]
	_ = x[OpCodeFuncSave-26]
	_ = x[OpCodeFuncShowDump-27]
	_ = x[OpCodeFuncUnion-28]
	_ = x[OpCodeCommandChangeDir-29]
	_ = x[OpCodeCommandEmpty-30]
	_ = x[OpCodeCommandGetWorkingDir-31]
	_ = x[OpCodeCommandHelp-32]
	_ = x[OpCodeCommandListDir-33]
	_ = x[OpCodeCommandQuit-34]
	_ = x[OpCodeCommandVars-35]
	_ = x[OpCodeCommandSetPragma-36]
	_ = x[OpCodeCommandGetPragma-37]
}

const _OpCode_name = "OpCodeNoopOpCodeLoadGoroutineDumpOpCodeLoadFieldAccessorOpCodeLoadNumberOpCodeLoadStringOpCodeAssignmentOpCodePushBoolOpCodePushDumpOpCodeAddGoroutineOpCodeNextGoroutineOpCodeTempDumpOpCodeContainsOpCodeRegexMatchesOpCodeRegexNotMatchesOpCodeEqualOpCodeGreaterOpCodeGreaterEqualOpCodeLessOpCodeLessEqualOpCodeNotEqualOpCodeJumpIfFalseOpCodeJumpIfTrueOpCodeJumpToOpCodeFuncDiffOpCodeFuncIntersectOpCodeFuncLoadOpCodeFuncSaveOpCodeFuncShowDumpOpCodeFuncUnionOpCodeCommandChangeDirOpCodeCommandEmptyOpCodeCommandGetWorkingDirOpCodeCommandHelpOpCodeCommandListDirOpCodeCommandQuitOpCodeCommandVarsOpCodeCommandSetPragmaOpCodeCommandGetPragma"

var _OpCode_index = [...]uint16{0, 10, 33, 56, 72, 88, 104, 118, 132, 150, 169, 183, 197, 215, 236, 247, 260, 278, 288, 303, 317, 334, 350, 362, 376, 395, 409, 423, 441, 456, 478, 496, 522, 539, 559, 576, 593, 615, 637}

func (i OpCode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_OpCode_index)-1 {
		return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpCode_name[_OpCode_index[idx]:_OpCode_index[idx+1]]
}
