// Code generated by "stringer -type Tag -linecomment"; DO NOT EDIT.

package internal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TagNone-0]
	_ = x[TagBool-1]
	_ = x[TagNumber-2]
	_ = x[TagString-3]
	_ = x[TagIdentifier-4]
	_ = x[TagFieldAccessor-5]
	_ = x[TagCommand-6]
	_ = x[TagDump-7]
	_ = x[TagGoroutine-8]
	_ = x[TagAddress-9]
	_ = x[TagDiff-10]
	_ = x[TagMap-11]
}

const _Tag_name = "TagNoneboolnumberstringidentifierfield accessorcommanddumpgoroutineaddressdiffmap"

var _Tag_index = [...]uint8{0, 7, 11, 17, 23, 33, 47, 54, 58, 67, 74, 78, 81}

func (i Tag) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Tag_index)-1 {
		return "Tag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Tag_name[_Tag_index[idx]:_Tag_index[idx+1]]
}
