// Code generated by "stringer -type TokenType -linecomment"; DO NOT EDIT.

package internal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenInvalid-0]
	_ = x[TokenPipe-1]
	_ = x[TokenLeftParen-2]
	_ = x[TokenRightParen-3]
	_ = x[TokenPlus-4]
	_ = x[TokenMinus-5]
	_ = x[TokenStar-6]
	_ = x[TokenSlash-7]
	_ = x[TokenBang-8]
	_ = x[TokenComma-9]
	_ = x[TokenAssign-10]
	_ = x[TokenEqual-11]
	_ = x[TokenNotEqual-12]
	_ = x[TokenLessThan-13]
	_ = x[TokenLessEqualThan-14]
	_ = x[TokenGreaterThan-15]
	_ = x[TokenGreaterEqualThan-16]
	_ = x[TokenKeywordContains-17]
	_ = x[TokenIdentifier-18]
	_ = x[TokenString-19]
	_ = x[TokenNumber-20]
	_ = x[TokenFieldAccessor-21]
	_ = x[TokenKeywordAnd-22]
	_ = x[TokenKeywordOr-23]
	_ = x[TokenCommand-24]
	_ = x[TokenFunction-25]
	_ = x[TokenMethod-26]
	_ = x[TokenPragma-27]
}

const _TokenType_name = "invalidpipeleft parenright paren+-*/!,===!=<<=>>=containsidentifierstringnumberfield accessorandorcommandfunctionmethodpragma"

var _TokenType_index = [...]uint8{0, 7, 11, 21, 32, 33, 34, 35, 36, 37, 38, 39, 41, 43, 44, 46, 47, 49, 57, 67, 73, 79, 93, 96, 98, 105, 113, 119, 125}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
