// Code generated by "stringer -type TokenType -linecomment"; DO NOT EDIT.

package internal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenInvalid-0]
	_ = x[TokenPipe-1]
	_ = x[TokenLeftParen-2]
	_ = x[TokenRightParen-3]
	_ = x[TokenPlus-4]
	_ = x[TokenMinus-5]
	_ = x[TokenStar-6]
	_ = x[TokenSlash-7]
	_ = x[TokenBang-8]
	_ = x[TokenComma-9]
	_ = x[TokenAssign-10]
	_ = x[TokenEqual-11]
	_ = x[TokenNotEqual-12]
	_ = x[TokenLessThan-13]
	_ = x[TokenLessEqualThan-14]
	_ = x[TokenGreaterThan-15]
	_ = x[TokenGreaterEqualThan-16]
	_ = x[TokenKeywordContains-17]
	_ = x[TokenKeywordMatches-18]
	_ = x[TokenRegexMatch-19]
	_ = x[TokenRegexNotMatch-20]
	_ = x[TokenIdentifier-21]
	_ = x[TokenString-22]
	_ = x[TokenNumber-23]
	_ = x[TokenFieldAccessor-24]
	_ = x[TokenKeywordAnd-25]
	_ = x[TokenKeywordOr-26]
	_ = x[TokenCommand-27]
	_ = x[TokenFunction-28]
	_ = x[TokenMethod-29]
	_ = x[TokenPragma-30]
}

const _TokenType_name = "invalidpipeleft parenright paren+-*/!,===!=<<=>>=containsmatch=~!~identifierstringnumberfield accessorandorcommandfunctionmethodpragma"

var _TokenType_index = [...]uint8{0, 7, 11, 21, 32, 33, 34, 35, 36, 37, 38, 39, 41, 43, 44, 46, 47, 49, 57, 62, 64, 66, 76, 82, 88, 102, 105, 107, 114, 122, 128, 134}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
